CREATE SEQUENCE SEQUENTIAL_PERSON_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1;

CREATE TABLE SEQUENTIAL_PERSON
(
    ID         LONG         NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME  VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
)
